require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/shelters', type: :request do
  # Shelter. As you add validations to Shelter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Shelter.create! valid_attributes
      get shelters_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      shelter = Shelter.create! valid_attributes
      get shelter_url(shelter)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_shelter_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      shelter = Shelter.create! valid_attributes
      get edit_shelter_url(shelter)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Shelter' do
        expect do
          post shelters_url, params: { shelter: valid_attributes }
        end.to change(Shelter, :count).by(1)
      end

      it 'redirects to the created shelter' do
        post shelters_url, params: { shelter: valid_attributes }
        expect(response).to redirect_to(shelter_url(Shelter.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Shelter' do
        expect do
          post shelters_url, params: { shelter: invalid_attributes }
        end.to change(Shelter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post shelters_url, params: { shelter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested shelter' do
        shelter = Shelter.create! valid_attributes
        patch shelter_url(shelter), params: { shelter: new_attributes }
        shelter.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the shelter' do
        shelter = Shelter.create! valid_attributes
        patch shelter_url(shelter), params: { shelter: new_attributes }
        shelter.reload
        expect(response).to redirect_to(shelter_url(shelter))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shelter = Shelter.create! valid_attributes
        patch shelter_url(shelter), params: { shelter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested shelter' do
      shelter = Shelter.create! valid_attributes
      expect do
        delete shelter_url(shelter)
      end.to change(Shelter, :count).by(-1)
    end

    it 'redirects to the shelters list' do
      shelter = Shelter.create! valid_attributes
      delete shelter_url(shelter)
      expect(response).to redirect_to(shelters_url)
    end
  end
end
